background   = "#282C34"
panel_bg     = "#1D2025"
text         = "#ABB2BF"
accent       = "#414754"
button       = "#414754"
button_hover = "#4f5564"
button_text  = "#CCCCCC"
error        = "#E06C75"
warning      = "#D19A66"
success      = "#98C379"
info         = "#61AFEF"